// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlueRoom.Data.Configurations;
using BlueRoom.Models;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace BlueRoom.Data
{
    public partial class BlueRoomContext : DbContext
    {
        public BlueRoomContext()
        {
        }

        public BlueRoomContext(DbContextOptions<BlueRoomContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<SetNumber> SetNumbers { get; set; }
        public virtual DbSet<Show> Shows { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
        public virtual DbSet<SongPerformance> SongPerformances { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ShowConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SongConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SongPerformanceConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
