// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BlueRoom.Models
{
    [Table("show")]
    public partial class Show
    {
        public Show()
        {
            SongPerformances = new HashSet<SongPerformance>();
        }

        [Key]
        [Column("show_id")]
        public int ShowId { get; set; }
        [Column("date")]
        public DateTime Date { get; set; }
        [Column("venue_id")]
        public int VenueId { get; set; }
        [Column("performing_artist_id")]
        public int PerformingArtistId { get; set; }

        [ForeignKey(nameof(PerformingArtistId))]
        [InverseProperty(nameof(Artist.Shows))]
        public virtual Artist PerformingArtist { get; set; }
        [InverseProperty(nameof(SongPerformance.Show))]
        public virtual ICollection<SongPerformance> SongPerformances { get; set; }
    }
}