// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BlueRoom.Models
{
    [Table("song_performance")]
    public partial class SongPerformance
    {
        [Key]
        [Column("song_performance_id")]
        public int SongPerformanceId { get; set; }
        [Column("set_number_id")]
        public int SetNumberId { get; set; }
        [Column("song_performance_name")]
        [StringLength(255)]
        public string SongPerformanceName { get; set; }
        [Column("set_song_index")]
        public int SetSongIndex { get; set; }
        [Column("duration")]
        public int? Duration { get; set; }
        [Column("media_link_id")]
        public int? MediaLinkId { get; set; }
        [Column("show_id")]
        public int ShowId { get; set; }
        [Column("song_id")]
        public int? SongId { get; set; }

        [ForeignKey(nameof(SetNumberId))]
        [InverseProperty("SongPerformances")]
        public virtual SetNumber SetNumber { get; set; }
        [ForeignKey(nameof(ShowId))]
        [InverseProperty("SongPerformances")]
        public virtual Show Show { get; set; }
        [ForeignKey(nameof(SongId))]
        [InverseProperty("SongPerformances")]
        public virtual Song Song { get; set; }
    }
}