// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entities.Models
{
    public partial class SetNumber
    {
        public SetNumber()
        {
            SongPerformances = new HashSet<SongPerformance>();
        }

        public int SetNumberId { get; set; }
        public int SetIndex { get; set; }
        public string SetName { get; set; }
        public bool FullSet { get; set; }

        public ICollection<SongPerformance> SongPerformances { get; set; }
    }
}