// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entities.Models
{
    public partial class Show
    {
        public Show()
        {

        }

        public int ShowId { get; set; }
        public DateTime Date { get; set; }
        public int VenueId { get; set; }
        public int PerformingArtistId { get; set; }

        public Artist PerformingArtist { get; set; }
        public Venue Venue { get; set; }
        public ICollection<SongPerformance> SongPerformances { get; set; }
    }
}