// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entities.Models
{
    public partial class Song
    {
        public Song()
        {
            SongPerformances = new HashSet<SongPerformance>();
        }

        public int SongId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? OriginalArtistId { get; set; }
        public string OriginalArtistName { get; set; }

        public Artist OriginalArtist { get; set; }
        public ICollection<SongPerformance> SongPerformances { get; set; }
    }
}