// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entities.Models
{
    public partial class SongPerformance
    {
        public int SongPerformanceId { get; set; }
        public int SetNumberId { get; set; }
        public string SongPerformanceNote { get; set; }
        public int SetSongIndex { get; set; }
        public int? DurationInSec { get; set; }
        public int? MediaLinkId { get; set; }
        public int ShowId { get; set; }
        public int SongId { get; set; }
        public bool SegueOut { get; set; }
        public bool SetOpener { get; set; }
        public bool SetCloser { get; set; }

        public SetNumber SetNumber { get; set; }
        public Show Show { get; set; }
        public Song Song { get; set; }
    }
}