// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entities.Models
{
    public partial class Venue
    {
        public Venue()
        {
            Shows = new HashSet<Show>();
        }

        public int VenueId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }

        public ICollection<Show> Shows { get; set; }
    }
}