// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Entities.Models
{
    public partial class VwShow
    {
        public int ShowId { get; set; }
        public DateTime Date { get; set; }
        public string ArtistName { get; set; }
        public int ArtistId { get; set; }
        public int VenueId { get; set; }
        public string VenueName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}