// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlueRoom.Data;
using BlueRoom.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace BlueRoom.Data.Configurations
{
    public partial class ShowConfiguration : IEntityTypeConfiguration<Show>
    {
        public void Configure(EntityTypeBuilder<Show> entity)
        {
            entity.HasOne(d => d.PerformingArtist)
                .WithMany(p => p.Shows)
                .HasForeignKey(d => d.PerformingArtistId)
                .HasConstraintName("FK_Show_Artist_performing_artist_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Show> entity);
    }
}
