// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlueRoom.Data;
using BlueRoom.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace BlueRoom.Data.Configurations
{
    public partial class SongPerformanceConfiguration : IEntityTypeConfiguration<SongPerformance>
    {
        public void Configure(EntityTypeBuilder<SongPerformance> entity)
        {
            entity.HasOne(d => d.SetNumber)
                .WithMany(p => p.SongPerformances)
                .HasForeignKey(d => d.SetNumberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Song_Performance_Set_Number_set_number_id");

            entity.HasOne(d => d.Show)
                .WithMany(p => p.SongPerformances)
                .HasForeignKey(d => d.ShowId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Song_Performance_Show_show_id");

            entity.HasOne(d => d.Song)
                .WithMany(p => p.SongPerformances)
                .HasForeignKey(d => d.SongId)
                .HasConstraintName("FK_Song_Performance_Song_song_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SongPerformance> entity);
    }
}
