// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BlueRoom.Data;
using BlueRoom.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace BlueRoom.Data.Configurations
{
    public partial class SongConfiguration : IEntityTypeConfiguration<Song>
    {
        public void Configure(EntityTypeBuilder<Song> entity)
        {
            entity.HasOne(d => d.OriginalArtist)
                .WithMany(p => p.Songs)
                .HasForeignKey(d => d.OriginalArtistId)
                .HasConstraintName("FK_Song_Artist_original_artist_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Song> entity);
    }
}
