// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Entities.Models;

#nullable disable

namespace Entities.Context
{
    public partial class BlueRoomContext : DbContext
    {
        public BlueRoomContext()
        {
        }

        public BlueRoomContext(DbContextOptions<BlueRoomContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Show> Shows { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
        public virtual DbSet<SongPerformance> SongPerformances { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Show>(entity =>
            {
                entity.HasOne(d => d.PerformingArtist)
                    .WithMany(p => p.Shows)
                    .HasForeignKey(d => d.PerformingArtistId)
                    .HasConstraintName("FK_Show_Artist_performing_artist_id");
            });

            modelBuilder.Entity<Song>(entity =>
            {
                entity.HasOne(d => d.OriginalArtist)
                    .WithMany(p => p.Songs)
                    .HasForeignKey(d => d.OriginalArtistId)
                    .HasConstraintName("FK_Song_Artist_original_artist_id");
            });

            modelBuilder.Entity<SongPerformance>(entity =>
            {
                entity.HasOne(d => d.SetNumber)
                    .WithMany(p => p.SongPerformances)
                    .HasForeignKey(d => d.SetNumberId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Song_Performance_Set_Number_set_number_id");

                entity.HasOne(d => d.Show)
                    .WithMany(p => p.SongPerformances)
                    .HasForeignKey(d => d.ShowId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Song_Performance_Show_show_id");

                entity.HasOne(d => d.Song)
                    .WithMany(p => p.SongPerformances)
                    .HasForeignKey(d => d.SongId)
                    .HasConstraintName("FK_Song_Performance_Song_song_id");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}