// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Entities.Models
{
    [Table("set_number")]
    public partial class SetNumber
    {
        public SetNumber()
        {
            SongPerformances = new HashSet<SongPerformance>();
        }

        [Key]
        [Column("set_number_id")]
        public int SetNumberId { get; set; }
        [Column("set_index")]
        public int SetIndex { get; set; }
        [Column("set_name")]
        [StringLength(255)]
        public string SetName { get; set; }
        [Column("full_set")]
        public bool FullSet { get; set; }

        [InverseProperty(nameof(SongPerformance.SetNumber))]
        public virtual ICollection<SongPerformance> SongPerformances { get; set; }
    }
}